[package]
name = "hash-chain"
version = "0.1.0"
authors = ["Sirius <sirius@x250>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16"
hex = "0.4.0"
